/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.github.lambda.gateway.swagger.server.api;

import com.github.lambda.gateway.swagger.model.WebsocketMessageBase;
import com.github.lambda.gateway.swagger.model.WebsocketMessageInclusive;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Optional;

@Api(value = "WebsocketController", description = "the WebsocketController API")
public interface WebsocketControllerApi {

    Logger log = LoggerFactory.getLogger(WebsocketControllerApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "", nickname = "connection", notes = "", response = WebsocketMessageInclusive.class, tags={ "websocket-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = WebsocketMessageInclusive.class) })
    @RequestMapping(value = "/pseudo/controller/websocket",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<WebsocketMessageInclusive> connection(@ApiParam(value = ""  )  @Valid @RequestBody WebsocketMessageBase body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"notification\" : {    \"header\" : {      \"stage\" : { },      \"failure\" : {        \"path\" : \"path\",        \"code\" : 6,        \"stacktrace\" : \"stacktrace\",        \"message\" : \"message\",        \"type\" : \"type\",        \"timestamp\" : 0      },      \"segment\" : { },      \"destination\" : [ \"destination\", \"destination\" ],      \"type\" : { }    },    \"body\" : {      \"message\" : \"message\"    }  }}", WebsocketMessageInclusive.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default WebsocketControllerApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
