version: '3.5'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
    - 3306:3306
    environment:
    - MYSQL_DATABASE=application
    - MYSQL_ROOT_PASSWORD=root
    - LANG=C.UTF-8
    volumes:
    - ./script/docker-mysql/:/etc/mysql/conf.d

  redis:
    image: redis:4
    container_name: redis
    restart: always
    ports:
    - 6379:6379
