export const PRODUCT__FETCH_PAGINATED_ITEMS = "PRODUCT/FETCH_PAGINATED_ITEMS"
export const PRODUCT__FETCH_PAGINATED_ITEMS_FAIL = "PRODUCT/FETCH_PAGINATED_ITEMS:FAIL"
export const PRODUCT__FETCH_PAGINATED_ITEMS_DONE = "PRODUCT/FETCH_PAGINATED_ITEMS:DONE"
