/**
 * AUTH
 */

export const AUTH__LOGIN = "AUTH/LOGIN"
export const AUTH__REGISTER = "AUTH/REGISTER"

/**
 * PRODUCT
 */
export const PRODUCT__FETCH_PAGINATED_ITEMS = "PRODUCT/FETCH_PAGINATED_ITEMS"
export const PRODUCT__FETCH_CATEGORY_LIST = "PRODUCT/FETCH_CATEGORY_LIST"

/**
 * DETAIL
 */
export const DETAIL__FETCH_PRODUCT_ITEM = "DETAIL/FETCH_PRODUCT_ITEM"
export const DETAIL__ADD_TO_CART = "DETAIL/ADD_TO_CART"

/**
 * CART
 */

export const CART__FETCH_CART_LINE_LIST = "CART/FETCH_CART_LINE_LIST"
export const CART__UPDATE_CART_LINE = "CART/UPDATE_CART_LINE"
export const CART__REMOVE_CART_LINE = "CART/REMOVE_CART_LINE"
export const CART__REMOVE_CART_LINE_LIST = "CART/REMOVE_CART_LINE_LIST"

// TODO
export const DETAIL__FETCH_CATEGORY_SIBLINGS = "DETAIL/FETCH_CATEGORY_SIBLINGS"
