export const PRODUCT__UPDATE_ITEMS = "PRODUCT/UPDATE_ITEMS"
export const PRODUCT__UPDATE_TOTAL_COUNT = "PRODUCT/UPDATE_TOTAL_COUNT"
export const PRODUCT__UPDATE_CURRENT_PAGE = "PRODUCT/UPDATE_CURRENT_PAGE"
export const AUTH_UPDATE_USER = "AUTH/UPDATE_USER"