/**
 * AUTH
 */
export const AUTH__LOGOUT = "AUTH/LOGOUT"
export const AUTH__LOGIN = "AUTH/LOGOUT"
export const AUTH__SET_FLASH_MESSAGE = "AUTH/SET_FLASH_MESSAGE"
export const AUTH__CLEAR_FLASH_MESSAGE = "AUTH/CLEAR_FLASH_MESSAGE"

/**
 * PRODUCT
 */
export const PRODUCT__UPDATE_ITEMS = "PRODUCT/UPDATE_ITEMS"
export const PRODUCT__UPDATE_FILTER_PRICE = "PRODUCT/UPDATE_FILTER_PRICE"
export const PRODUCT__RESET_FILTER_PRICE = "PRODUCT/RESET_FILTER_PRICE"

export const PRODUCT__UPDATE_ITEM_COUNT_PER_PAGE = "PRODUCT/SET_ITEM_COUNT"
export const PRODUCT__UPDATE_TOTAL_ITEM_COUNT = "PRODUCT/UPDATE_TOTAL_ITEM_COUNT"
export const PRODUCT__UPDATE_CURRENT_PAGE = "PRODUCT/UPDATE_CURRENT_PAGE"

export const PRODUCT__SEARCH_UPDATE_KEYWORD = "PRODUCT/SEARCH/UPDATE_KEYWORD"
export const PRODUCT__SEARCH_UPDATE_CATEGORY = "PRODUCT/SEARCH/UPDATE_CATEGORY"
export const PRODUCT__SEARCH_UPDATE_CATEGORY_LIST = "PRODUCT/SEARCH/UPDATE_CATEGORY_LIST"

/**
 * DETAIL
 */

export const DETAIL__SET_PRODUCT_ITEM = "DETAIL/SET_PRODUCT_ITEM"
export const DETAIL__SET_PRODUCT_OPTION_LIST = "DETAIL/SET_PRODUCT_OPTION_LIST"
export const DETAIL__SET_QUANTITY = "DETAIL/SET_QUANTITY"

/**
 * CART
 */

export const CART__SET_CART_LINE_LIST = "CART/SET_LINE_LIST"
