export const PRODUCT__FETCHED_ITEMS = "PRODUCT/FETCHED_ITEMS"

export const PRODUCT__FILTER_MIN_PRICE = "PRODUCT/FILTER/MIN_PRICE"
export const PRODUCT__FILTER_MAX_PRICE = "PRODUCT/FILTER/MAX_PRICE"

export const AUTH__USERNAME = "username"
export const AUTH__FLASH_MESSAGE = "flashMessage"

export const PRODUCT__TOTAL_COUNT = "PRODUCT/PAGINATION/TOTAL_COUNT"
export const PRODUCT__CURRENT_PAGE = "PRODUCT/PAGINATION/CURRENT_PAGE"
export const PRODUCT__CURRENT_SIZE = "PRODUCT/PAGINATION/CURRENT_SIZE" // pagination size

export const PRODUCT__SEARCH_KEYWORD = "PRODUCT/SEARCH/KEYWORD"
export const PRODUCT__SEARCH_CATEGORY = "PRODUCT/SEARCH/CATEGORY"
export const PRODUCT__SEARCH_AVAILABLE_CATEGORIES = "PRODUCT/SEARCH/AVAILABLE_CATEGORIES"
