/**
 * DEFAULT STATE
 */

/**
 * AUTH
 */
export const AUTH__USERNAME = "AUTH/USERNAME"
export const AUTH__FLASH_MESSAGE = "AUTH.FLASH_MESSAGE"

/**
 * PRODUCT
 */
export const PRODUCT__FETCHED_ITEMS = "PRODUCT/FETCHED_ITEMS"
export const PRODUCT__FILTER_MIN_PRICE = "PRODUCT/FILTER/MIN_PRICE"
export const PRODUCT__FILTER_MAX_PRICE = "PRODUCT/FILTER/MAX_PRICE"

export const PRODUCT__TOTAL_COUNT = "PRODUCT/PAGINATION/TOTAL_COUNT"
export const PRODUCT__CURRENT_PAGE = "PRODUCT/PAGINATION/CURRENT_PAGE"
export const PRODUCT__CURRENT_SIZE = "PRODUCT/PAGINATION/CURRENT_SIZE" // pagination size

export const PRODUCT__SEARCH_KEYWORD = "PRODUCT/SEARCH/KEYWORD"
export const PRODUCT__SEARCH_CATEGORY = "PRODUCT/SEARCH/CATEGORY"
export const PRODUCT__SEARCH_AVAILABLE_CATEGORIES = "PRODUCT/SEARCH/AVAILABLE_CATEGORIES"

/**
 * DETAIL
 */
export const DETAIL__PRODUCT_ITEM = "DETAIL/PRODUCT_ITEM"
export const DETAIL__PRODUCT_OPTION_LIST = "DETAIL/PRODUCT_OPTION_LIST"
export const DETAIL__PRODUCT_QUANTITY = "DETAIL/PRODUCT_QUANTITY"
export const DETAIL__REVIEW_RATE  = "DETAIL/REVIEW_RATE"
export const DETAIL__PRODUCT_ID = "DETAIL/PRODUCT_ID"

/**
 * CART
 */

export const CART__LINE_LIST = "CART/LINE_LIST"
export const CART__SELECT_LINE_ID_LIST = "CART/SELECT_LINE_ID_LIST"

