logging:
  level:
    ROOT: INFO

    # application
    com.github.lambda.gateway: DEBUG                         # application

    # security
    org.springframework.security: INFO


spring:
  application:
    name: Admin
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: local

#
# spring.security
#
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}
      roles: ACTUACTOR

#
# server
#
server:
  port: ${APPLICATION_PORT:8099}
  servlet:
    session:
      cookie:
        http-only: true


