/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CategoryListDTO;
import io.swagger.model.Failure;
import io.swagger.model.ProductDTO;
import io.swagger.model.ProductListDTO;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-10-15T16:52:04.159+09:00")

@Api(value = "catalog", description = "the catalog API")
public interface CatalogApi {

    @ApiOperation(value = "", nickname = "findAllCategories", notes = "", response = CategoryListDTO.class, tags={ "catalog-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = CategoryListDTO.class),
        @ApiResponse(code = 200, message = "error", response = Failure.class) })
    @RequestMapping(value = "/catalog/categories",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CategoryListDTO> findAllCategories();


    @ApiOperation(value = "", nickname = "findOneProduct", notes = "", response = ProductDTO.class, tags={ "catalog-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ProductDTO.class),
        @ApiResponse(code = 200, message = "error", response = Failure.class) })
    @RequestMapping(value = "/catalog/product/{productId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ProductDTO> findOneProduct(@ApiParam(value = "",required=true) @PathVariable("productId") Long productId);


    @ApiOperation(value = "", nickname = "findPaginatedProducts", notes = "", response = ProductListDTO.class, tags={ "catalog-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ProductListDTO.class),
        @ApiResponse(code = 200, message = "error", response = Failure.class) })
    @RequestMapping(value = "/catalog/products",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ProductListDTO> findPaginatedProducts(@ApiParam(value = "",required=true) @PathVariable("productId") Long productId,@ApiParam(value = "",required=true) @PathVariable("page") Long page,@ApiParam(value = "",required=true) @PathVariable("count") Long count);

}
