spring.profiles.include:
- test

# http logging
logbook:
  filter.enabled: false

spring:

#
# spring.flyway
#
  flyway:
    enabled: true
    check-location: true
    locations: classpath:/db/migration/data-h2
