logging:
  level:
    ROOT: INFO

    # application
    com.github.lambda.gateway: DEBUG # application

    # JPA
    org.hibernate.SQL: DEBUG                                    # hibernate
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE        # hibernate
    org.hibernate.type.EnumType: TRACE                          # hibernate

    org.springframework.transaction: DEBUG                      # transaction
    org.springframework.orm.jpa: DEBUG                          # transaction

    org.springframework.jdbc.core.JdbcTemplate: DEBUG           # JDBC
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE  # JDBC

    # security
    org.springframework.security: DEBUG

spring.jpa.show-sql: false # Use logger output instead
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.generate_statistics: false
spring.jpa.properties.hibernate.type: TRACE

# http logging
logbook:
  filter.enabled: true
  format.style: http
  obfuscate:
    headers:
    - NONE
  write:
    category: http.wire-log
    level: INFO
    chunk-size: 1000

spring:

#
# spring.datasource
#
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:application;DB_CLOSE_DELAY=-1;MODE=MYSQL;
    username: sa
    password: sa
    hikari:
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 048
        useServerPrepStmts: true

#
# spring.jpa
#
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: update

#
# spring.security
#
  security:
    user:
      name: ${ACTUACTOR_USERNAME:admin}
      password: ${ACTUACTOR_PASSWORD:admin}
      roles: ACTUACTOR

#
# spring session and redis
#
  session.store-type: redis
  data.redis.repositories.enabled: true

server:
  port: ${APPLICATION_PORT:8090}
  servlet:
    session:
      cookie:
        http-only: true


