swagger: "2.0"
info:
  description: "A blog API."
  version: "1.0.0"
  title: "Blog API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

host: "blog.acme.io"
basePath: "/v1"

tags:
- name: "post"
  description: "Managing posts"
- name: "comment"
  description: "Managing comments"

schemes:
- "http"

paths:
  /post:
    get:
      tags:
      - "post"
      summary: "Get most recent posts"
      responses:
        200:
          description: "List of posts"
          schema:
            type: array
            items:
              $ref: '#/definitions/Post'
    post:
      tags:
      - "post"
      summary: "Add a new blog post"
      parameters:
      - in: "body"
        name: "body"
        description: "Blog post information"
        required: true
        schema:
          $ref: "#/definitions/Post"
      responses:
        405:
          description: "Invalid input"
  /post/{postId}:
    get:
      tags:
      - "post"
      summary: "Find blog post by ID"
      description: "Returns a single blog post"
      parameters:
      - name: "postId"
        in: "path"
        description: "ID of post to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Post"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
    post:
      tags:
      - "post"
      summary: "Updates a blog post in the store"
      parameters:
      - name: "postId"
        in: "path"
        description: "ID of pet that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Blog post information"
        required: true
        schema:
          $ref: "#/definitions/Post"
      responses:
        405:
          description: "Invalid input"
    delete:
      tags:
      - "post"
      summary: "Deletes a blog post"
      parameters:
      - name: "postId"
        in: "path"
        description: "ID of blog post to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Blog post not found"
  /post/{postId}/comment:
    post:
      summary: "Create new comment"
      tags:
      - "comment"
      responses:
        404:
          description: "Post not found"
    parameters:
    - name: "postId"
      in: "path"
      required: true
      type: "integer"
      format: "int64"

definitions:
  Post:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      body:
        type: "string"
        writeOnly: true
      author:
        type: "string"
      createdAt:
        type: "string"
        format: "date-time"
        writeOnly: true
      comments:
        type: "array"
        items:
          $ref: "#/definitions/Comment"
  Comment:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
      body:
        type: "string"
      author:
        type: "string"
      createdAt:
        type: "string"
        format: "date-time"
        readOnly: true
