logging:
  level:
    ROOT: INFO
    com.github.lambda.playground: DEBUG                         # application

    org.hibernate.SQL: DEBUG                                    # hibernate
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE        # hibernate

    org.springframework.transaction: DEBUG                      # transaction
    org.springframework.orm.jpa: DEBUG                          # transaction

    org.springframework.jdbc.core.JdbcTemplate: DEBUG           # JDBC
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE  # JDBC

spring.jpa.show-sql: false # Use logger output instead
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.generate_statistics: false

#
# spring actuactor
#
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"
    metrics:
      enabled: true
    prometheus:
      enabled: true
  # https://dzone.com/articles/monitoring-using-spring-boot-2-prometheus-and-graf
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    git:
      mode: full
  health:
    defaults:
      enabled: true
    mail:
      enabled: false

spring:

#
# spring.flyway
#
  flyway:
    enabled: true
    check-location: true
    locations: classpath:/db/migration/schema,classpath:/db/migration/data-mysql

#
# spring.datasource
#
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:application}?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

#
# spring.jpa
#
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    open-in-view: false
    hibernate:
      ddl-auto: validate

#
# spring.security
#
  security:
    user:
      name: ${ACTUACTOR_USERNAME:admin}
      password: ${ACTUACTOR_PASSWORD:admin}
      roles: ACTUACTOR
